# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

sshd_packages:
- core/openssh

sshd_keygen_service: sshdgenkeys.service
sshd_service: sshd
sftp_subsystem: /usr/lib/ssh/sftp-server

sshd_config_has_global_include: false
sshd_config_default_mode: '0644'
sshd_gssapiauth: 'no'
sshd_syslogfacility: AUTH

...
